import test from 'node:test'
import assert from 'node:assert/strict'
import {
  buildRecipeDocumentTemplate,
  buildRecipeDocumentRequests,
} from './recipeDocumentTemplate.js'

const sampleRecipe = {
  name: 'Lemon Pasta',
  description: 'Bright weeknight pasta',
  category: 'Dinner',
  servings: 2,
  prepTime: 10,
  cookTime: 15,
  ingredients: [
    { name: 'Pasta', amount: 200, unit: 'g', calories: 700 },
    { name: 'Lemon', amount: 1, unit: 'piece', calories: 20 },
  ],
  instructions: ['Boil pasta', 'Toss with lemon'],
  totalCalories: 720,
  caloriesPerServing: 360,
}

test('buildRecipeDocumentTemplate produces a display-ready title and summary block', () => {
  const template = buildRecipeDocumentTemplate(sampleRecipe)

  assert.equal(template.title, 'Lemon Pasta')

  const summary = Object.fromEntries(template.summary.map((fact) => [fact.label, fact.value]))
  assert.equal(summary['Category'], 'Dinner')
  assert.equal(summary['Servings'], '2')
  assert.equal(summary['Total Time'], '25 min')
  assert.equal(summary['Total Calories'], '720 kcal')
  assert.equal(summary['Per Serving'], '360 kcal')
})

test('buildRecipeDocumentTemplate includes the description when present and omits it when blank', () => {
  const withDescription = buildRecipeDocumentTemplate(sampleRecipe)
  assert.equal(withDescription.description, 'Bright weeknight pasta')

  const blank = buildRecipeDocumentTemplate({ ...sampleRecipe, description: '   ' })
  assert.ok(!('description' in blank), 'blank descriptions must be omitted, not blanked out')
})

test('buildRecipeDocumentTemplate omits missing summary facts instead of showing zeros', () => {
  const sparse = buildRecipeDocumentTemplate({
    name: 'Mystery Dish',
    servings: 4,
    ingredients: [],
    instructions: [],
  })

  const labels = sparse.summary.map((fact) => fact.label)
  assert.deepEqual(labels, ['Servings'])
  assert.equal(sparse.summary[0].value, '4')
})

test('buildRecipeDocumentTemplate builds display-ready ingredient rows with neutral calories when missing', () => {
  const template = buildRecipeDocumentTemplate({
    name: 'Mixed',
    ingredients: [
      { name: 'Pasta', amount: 200, unit: 'g', calories: 700 },
      { name: 'Water', amount: 1, unit: 'L' },
      { name: 'Salt', amount: 1, unit: 'pinch', calories: 0 },
    ],
    instructions: [],
  })

  assert.deepEqual(template.ingredients, [
    { name: 'Pasta', amount: '200', unit: 'g', calories: '700 kcal' },
    { name: 'Water', amount: '1', unit: 'L', calories: null },
    { name: 'Salt', amount: '1', unit: 'pinch', calories: '0 kcal' },
  ])
})

test('buildRecipeDocumentTemplate keeps instruction steps and a subtle generated-by footer', () => {
  const template = buildRecipeDocumentTemplate(sampleRecipe)

  assert.deepEqual(template.instructions, ['Boil pasta', 'Toss with lemon'])
  assert.match(template.footer, /Generated by My Cookbook/)
})

// ─── Request builder ─────────────────────────────────────────────────────────

function insertedText(requests) {
  return requests
    .filter((request) => request.insertText)
    .map((request) => request.insertText.text)
    .join('')
}

test('buildRecipeDocumentRequests renders the title as a styled heading', () => {
  const requests = buildRecipeDocumentRequests(buildRecipeDocumentTemplate(sampleRecipe))

  const titleInsert = requests.find(
    (request) => request.insertText && request.insertText.text.startsWith('Lemon Pasta')
  )
  assert.ok(titleInsert, 'expected the title to be inserted as document text')

  const { index } = titleInsert.insertText.location
  const titleStyle = requests.find(
    (request) =>
      request.updateParagraphStyle &&
      request.updateParagraphStyle.range.startIndex === index &&
      request.updateParagraphStyle.paragraphStyle.namedStyleType === 'TITLE'
  )
  assert.ok(titleStyle, 'expected the title paragraph to use the TITLE named style')
})

test('buildRecipeDocumentRequests renders ingredients as a real Google Docs table', () => {
  const requests = buildRecipeDocumentRequests(buildRecipeDocumentTemplate(sampleRecipe))

  const tableInsert = requests.find((request) => request.insertTable)
  assert.ok(tableInsert, 'expected a native insertTable request rather than plain text rows')
  assert.equal(tableInsert.insertTable.columns, 4)
  assert.equal(tableInsert.insertTable.rows, 3, 'expected a header row plus one row per ingredient')

  const text = insertedText(requests)
  assert.match(text, /Ingredient/)
  assert.match(text, /Calories/)
  for (const value of ['Pasta', '200', 'g', '700 kcal', 'Lemon', '1', 'piece', '20 kcal']) {
    assert.ok(text.includes(value), `expected table to contain "${value}"`)
  }
})

test('buildRecipeDocumentRequests leaves a neutral cell for ingredients without calories', () => {
  const requests = buildRecipeDocumentRequests(
    buildRecipeDocumentTemplate({
      name: 'Mixed',
      ingredients: [{ name: 'Water', amount: 1, unit: 'L' }],
      instructions: [],
    })
  )

  assert.equal(
    insertedText(requests).includes('0 kcal'),
    false,
    'missing per-ingredient calories must not be rendered as 0 kcal'
  )
})

test('buildRecipeDocumentRequests renders instructions as a native numbered list', () => {
  const requests = buildRecipeDocumentRequests(buildRecipeDocumentTemplate(sampleRecipe))

  const bullets = requests.find((request) => request.createParagraphBullets)
  assert.ok(bullets, 'expected instructions to use native list bullets, not manual numbering')
  assert.match(bullets.createParagraphBullets.bulletPreset, /NUMBERED/)

  const text = insertedText(requests)
  assert.match(text, /Boil pasta/)
  assert.match(text, /Toss with lemon/)
  assert.equal(
    /^\s*1\.\s/m.test(text),
    false,
    'steps must not be manually numbered as plain text'
  )
})

test('buildRecipeDocumentRequests places the description as a subtitle and omits it when blank', () => {
  const withDescription = buildRecipeDocumentRequests(buildRecipeDocumentTemplate(sampleRecipe))
  const descriptionInsert = withDescription.find(
    (request) => request.insertText && request.insertText.text.startsWith('Bright weeknight pasta')
  )
  assert.ok(descriptionInsert, 'expected the description to be inserted')
  const subtitle = withDescription.find(
    (request) =>
      request.updateParagraphStyle &&
      request.updateParagraphStyle.range.startIndex === descriptionInsert.insertText.location.index &&
      request.updateParagraphStyle.paragraphStyle.namedStyleType === 'SUBTITLE'
  )
  assert.ok(subtitle, 'expected the description paragraph to use the SUBTITLE named style')

  const withoutDescription = buildRecipeDocumentRequests(
    buildRecipeDocumentTemplate({ ...sampleRecipe, description: '' })
  )
  assert.equal(
    insertedText(withoutDescription).includes('Bright weeknight pasta'),
    false,
    'blank descriptions must not appear in the generated document'
  )
})

test('buildRecipeDocumentRequests includes the summary facts and footer text', () => {
  const requests = buildRecipeDocumentRequests(buildRecipeDocumentTemplate(sampleRecipe))
  const text = insertedText(requests)

  assert.match(text, /Servings/)
  assert.match(text, /360 kcal/)
  assert.match(text, /Generated by My Cookbook/)
})
