// Intermediate Recipe Document Template model and Google Docs request builders.
//
// buildRecipeDocumentTemplate turns a Recipe Record into display-ready
// presentation content (no Google Docs index mechanics).
//
// Generating a formatted Recipe Document is a two-pass operation because Google
// Docs cell indices cannot be predicted reliably (a table reserves structural
// index space and a newline is inserted before it):
//
//   1. buildRecipeDocumentSkeleton inserts every paragraph and an empty table by
//      appending to the end of the body, so it needs no index arithmetic.
//   2. After the skeleton is applied, the document is read back, and
//      buildRecipeDocumentFormatting uses the real indices from that read to fill
//      table cells and apply styling.

export function buildRecipeDocumentTemplate(recipe) {
  const template = {
    title: recipe.name || 'Recipe',
    summary: buildSummary(recipe),
    ingredients: buildIngredientRows(recipe),
    instructions: (recipe.instructions || []).filter((step) => String(step || '').trim() !== ''),
    footer: buildFooter(recipe),
  }

  const description = (recipe.description || '').trim()
  if (description) template.description = description

  return template
}

function buildFooter(recipe) {
  const updatedAt = recipe.updatedAt ? new Date(recipe.updatedAt) : null
  if (updatedAt && !Number.isNaN(updatedAt.getTime())) {
    const date = updatedAt.toISOString().slice(0, 10)
    return `Generated by My Cookbook · Updated ${date}`
  }
  return 'Generated by My Cookbook'
}

function buildSummary(recipe) {
  const totalTime = (recipe.prepTime || 0) + (recipe.cookTime || 0)
  const facts = [
    ['Category', recipe.category],
    ['Servings', recipe.servings],
    ['Total Time', totalTime ? `${totalTime} min` : null],
    ['Total Calories', recipe.totalCalories ? `${recipe.totalCalories} kcal` : null],
    ['Per Serving', recipe.caloriesPerServing ? `${recipe.caloriesPerServing} kcal` : null],
  ]

  return facts
    .filter(([, value]) => value !== null && value !== undefined && value !== '')
    .map(([label, value]) => ({ label, value: String(value) }))
}

function buildIngredientRows(recipe) {
  return (recipe.ingredients || []).map((ingredient) => ({
    name: ingredient.name || '',
    amount: ingredient.amount === undefined || ingredient.amount === null ? '' : String(ingredient.amount),
    unit: ingredient.unit || '',
    calories: hasCalories(ingredient.calories) ? `${ingredient.calories} kcal` : null,
  }))
}

function hasCalories(calories) {
  return calories !== undefined && calories !== null && calories !== ''
}

// ─── Document plan ────────────────────────────────────────────────────────────
//
// The ordered list of document blocks, shared by both passes so the skeleton and
// the formatting always agree on what appears and in what order.

const TABLE_HEADERS = ['Ingredient', 'Amount', 'Unit', 'Calories']

function planBlocks(template) {
  const blocks = []

  blocks.push({ kind: 'paragraph', text: template.title, namedStyleType: 'TITLE' })
  if (template.description) {
    blocks.push({ kind: 'paragraph', text: template.description, namedStyleType: 'SUBTITLE' })
  }
  if (template.summary.length) {
    blocks.push({ kind: 'paragraph', text: summaryLine(template.summary), subtle: true })
  }
  if (template.ingredients.length) {
    blocks.push({ kind: 'paragraph', text: 'Ingredients', namedStyleType: 'HEADING_1' })
    blocks.push({ kind: 'table', rows: ingredientTableRows(template.ingredients) })
  }
  if (template.instructions.length) {
    blocks.push({ kind: 'paragraph', text: 'Instructions', namedStyleType: 'HEADING_1' })
    blocks.push({ kind: 'list', items: template.instructions, bulletPreset: 'NUMBERED_DECIMAL_NESTED' })
  }
  if (template.footer) {
    blocks.push({ kind: 'paragraph', text: template.footer, subtle: true })
  }

  return blocks
}

function summaryLine(summary) {
  return summary.map((fact) => `${fact.label}: ${fact.value}`).join('  ·  ')
}

function ingredientTableRows(ingredients) {
  return [
    TABLE_HEADERS,
    ...ingredients.map((ingredient) => [
      ingredient.name,
      ingredient.amount,
      ingredient.unit,
      ingredient.calories ?? '',
    ]),
  ]
}

// ─── Pass 1: skeleton ─────────────────────────────────────────────────────────
//
// Appends every paragraph and an empty ingredient table to the end of the body.
// Using endOfSegmentLocation avoids any index arithmetic.

export function buildRecipeDocumentSkeleton(template) {
  const requests = []

  for (const block of planBlocks(template)) {
    if (block.kind === 'paragraph') {
      requests.push(appendParagraph(block.text))
    } else if (block.kind === 'list') {
      for (const item of block.items) requests.push(appendParagraph(item))
    } else if (block.kind === 'table') {
      requests.push({
        insertTable: {
          endOfSegmentLocation: {},
          rows: block.rows.length,
          columns: block.rows[0].length,
        },
      })
    }
  }

  return requests
}

function appendParagraph(text) {
  return { insertText: { endOfSegmentLocation: {}, text: `${text}\n` } }
}

// ─── Pass 2: formatting ───────────────────────────────────────────────────────
//
// Given the document body content read back after the skeleton was applied,
// produces the table cell text inserts and the styling requests. Requests are
// returned in descending start-index order so that the cell text inserts (the
// only requests that shift indices) never invalidate the indices of requests
// applied after them.

export function buildRecipeDocumentFormatting(template, bodyContent = []) {
  const elements = bodyContent.filter((element) => element.paragraph || element.table)
  const reader = new StructureReader(elements)
  const pending = []

  for (const block of planBlocks(template)) {
    if (block.kind === 'paragraph') {
      const paragraph = reader.nextParagraph()
      if (!paragraph) continue
      if (block.namedStyleType) pending.push(namedStyleRequest(paragraph, block.namedStyleType))
      if (block.subtle) pending.push(subtleStyleRequest(paragraph))
    } else if (block.kind === 'list') {
      const items = block.items.map(() => reader.nextParagraph()).filter(Boolean)
      if (items.length) pending.push(numberedListRequest(items, block.bulletPreset))
    } else if (block.kind === 'table') {
      const table = reader.nextTable()
      if (table) pending.push(...cellFillRequests(block.rows, table))
    }
  }

  return pending
    .sort((a, b) => b.sortIndex - a.sortIndex)
    .map((entry) => entry.request)
}

// Walks the body content in order, yielding the next non-empty paragraph or the
// next table on demand. Empty paragraphs (the document's own padding and the
// newline Google inserts before a table) are skipped.
class StructureReader {
  constructor(elements) {
    this.elements = elements
    this.cursor = 0
  }

  nextParagraph() {
    while (this.cursor < this.elements.length) {
      const element = this.elements[this.cursor]
      this.cursor += 1
      if (element.paragraph && paragraphText(element.paragraph) !== '') return element
    }
    return null
  }

  nextTable() {
    while (this.cursor < this.elements.length) {
      const element = this.elements[this.cursor]
      this.cursor += 1
      if (element.table) return element
    }
    return null
  }
}

function paragraphText(paragraph) {
  return (paragraph.elements || [])
    .map((element) => element.textRun?.content || '')
    .join('')
    .replace(/\n+$/, '')
    .trim()
}

function namedStyleRequest(paragraph, namedStyleType) {
  return {
    sortIndex: paragraph.startIndex,
    request: {
      updateParagraphStyle: {
        range: { startIndex: paragraph.startIndex, endIndex: paragraph.endIndex },
        paragraphStyle: { namedStyleType },
        fields: 'namedStyleType',
      },
    },
  }
}

function subtleStyleRequest(paragraph) {
  return {
    sortIndex: paragraph.startIndex,
    request: {
      updateTextStyle: {
        range: { startIndex: paragraph.startIndex, endIndex: paragraph.endIndex },
        textStyle: {
          fontSize: { magnitude: 9, unit: 'PT' },
          foregroundColor: { color: { rgbColor: { red: 0.4, green: 0.4, blue: 0.4 } } },
        },
        fields: 'fontSize,foregroundColor',
      },
    },
  }
}

function numberedListRequest(items, bulletPreset) {
  const startIndex = items[0].startIndex
  const endIndex = items[items.length - 1].endIndex
  return {
    sortIndex: startIndex,
    request: {
      createParagraphBullets: {
        range: { startIndex, endIndex },
        bulletPreset,
      },
    },
  }
}

function cellFillRequests(rows, tableElement) {
  const tableRows = tableElement.table?.tableRows || []
  const requests = []

  rows.forEach((cells, rowIndex) => {
    cells.forEach((value, columnIndex) => {
      const text = String(value ?? '')
      if (text === '') return
      const contentStart = tableRows[rowIndex]?.tableCells?.[columnIndex]?.content?.[0]?.startIndex
      if (contentStart == null) return
      requests.push({
        sortIndex: contentStart,
        request: { insertText: { location: { index: contentStart }, text } },
      })
    })
  })

  return requests
}
