import test from 'node:test'
import assert from 'node:assert/strict'
import {
  buildRecipeDocumentTemplate,
  buildRecipeDocumentRequests,
} from './recipeDocumentTemplate.js'

const sampleRecipe = {
  name: 'Lemon Pasta',
  description: 'Bright weeknight pasta',
  category: 'Dinner',
  servings: 2,
  prepTime: 10,
  cookTime: 15,
  ingredients: [
    { name: 'Pasta', amount: 200, unit: 'g', calories: 700 },
    { name: 'Lemon', amount: 1, unit: 'piece', calories: 20 },
  ],
  instructions: ['Boil pasta', 'Toss with lemon'],
  totalCalories: 720,
  caloriesPerServing: 360,
}

test('buildRecipeDocumentTemplate produces a display-ready title and summary block', () => {
  const template = buildRecipeDocumentTemplate(sampleRecipe)

  assert.equal(template.title, 'Lemon Pasta')

  const summary = Object.fromEntries(template.summary.map((fact) => [fact.label, fact.value]))
  assert.equal(summary['Category'], 'Dinner')
  assert.equal(summary['Servings'], '2')
  assert.equal(summary['Total Time'], '25 min')
  assert.equal(summary['Total Calories'], '720 kcal')
  assert.equal(summary['Per Serving'], '360 kcal')
})

test('buildRecipeDocumentTemplate includes the description when present and omits it when blank', () => {
  const withDescription = buildRecipeDocumentTemplate(sampleRecipe)
  assert.equal(withDescription.description, 'Bright weeknight pasta')

  const blank = buildRecipeDocumentTemplate({ ...sampleRecipe, description: '   ' })
  assert.ok(!('description' in blank), 'blank descriptions must be omitted, not blanked out')
})

test('buildRecipeDocumentTemplate omits missing summary facts instead of showing zeros', () => {
  const sparse = buildRecipeDocumentTemplate({
    name: 'Mystery Dish',
    servings: 4,
    ingredients: [],
    instructions: [],
  })

  const labels = sparse.summary.map((fact) => fact.label)
  assert.deepEqual(labels, ['Servings'])
  assert.equal(sparse.summary[0].value, '4')
})

test('buildRecipeDocumentTemplate builds display-ready ingredient rows with neutral calories when missing', () => {
  const template = buildRecipeDocumentTemplate({
    name: 'Mixed',
    ingredients: [
      { name: 'Pasta', amount: 200, unit: 'g', calories: 700 },
      { name: 'Water', amount: 1, unit: 'L' },
      { name: 'Salt', amount: 1, unit: 'pinch', calories: 0 },
    ],
    instructions: [],
  })

  assert.deepEqual(template.ingredients, [
    { name: 'Pasta', amount: '200', unit: 'g', calories: '700 kcal' },
    { name: 'Water', amount: '1', unit: 'L', calories: null },
    { name: 'Salt', amount: '1', unit: 'pinch', calories: '0 kcal' },
  ])
})

test('buildRecipeDocumentTemplate keeps instruction steps and a subtle generated-by footer', () => {
  const template = buildRecipeDocumentTemplate(sampleRecipe)

  assert.deepEqual(template.instructions, ['Boil pasta', 'Toss with lemon'])
  assert.match(template.footer, /Generated by My Cookbook/)
})
