// Intermediate Recipe Document Template model and Google Docs request builder.
//
// buildRecipeDocumentTemplate turns a Recipe Record into display-ready
// presentation content (no Google Docs index mechanics). buildRecipeDocumentRequests
// turns that content into native Google Docs batchUpdate requests.

export function buildRecipeDocumentTemplate(recipe) {
  const template = {
    title: recipe.name || 'Recipe',
    summary: buildSummary(recipe),
    ingredients: buildIngredientRows(recipe),
    instructions: (recipe.instructions || []).filter((step) => String(step || '').trim() !== ''),
    footer: buildFooter(recipe),
  }

  const description = (recipe.description || '').trim()
  if (description) template.description = description

  return template
}

function buildFooter(recipe) {
  const updatedAt = recipe.updatedAt ? new Date(recipe.updatedAt) : null
  if (updatedAt && !Number.isNaN(updatedAt.getTime())) {
    const date = updatedAt.toISOString().slice(0, 10)
    return `Generated by My Cookbook · Updated ${date}`
  }
  return 'Generated by My Cookbook'
}

function buildSummary(recipe) {
  const totalTime = (recipe.prepTime || 0) + (recipe.cookTime || 0)
  const facts = [
    ['Category', recipe.category],
    ['Servings', recipe.servings],
    ['Total Time', totalTime ? `${totalTime} min` : null],
    ['Total Calories', recipe.totalCalories ? `${recipe.totalCalories} kcal` : null],
    ['Per Serving', recipe.caloriesPerServing ? `${recipe.caloriesPerServing} kcal` : null],
  ]

  return facts
    .filter(([, value]) => value !== null && value !== undefined && value !== '')
    .map(([label, value]) => ({ label, value: String(value) }))
}

function buildIngredientRows(recipe) {
  return (recipe.ingredients || []).map((ingredient) => ({
    name: ingredient.name || '',
    amount: ingredient.amount === undefined || ingredient.amount === null ? '' : String(ingredient.amount),
    unit: ingredient.unit || '',
    calories: hasCalories(ingredient.calories) ? `${ingredient.calories} kcal` : null,
  }))
}

function hasCalories(calories) {
  return calories !== undefined && calories !== null && calories !== ''
}

export function buildRecipeDocumentRequests() {
  return []
}
