import test from 'node:test'
import assert from 'node:assert/strict'
import {
  buildRecipeDocumentTemplate,
  buildRecipeDocumentSkeleton,
  buildRecipeDocumentFormatting,
} from './recipeDocumentTemplate.js'

const sampleRecipe = {
  name: 'Lemon Pasta',
  description: 'Bright weeknight pasta',
  category: 'Dinner',
  servings: 2,
  prepTime: 10,
  cookTime: 15,
  ingredients: [
    { name: 'Pasta', amount: 200, unit: 'g', calories: 700 },
    { name: 'Lemon', amount: 1, unit: 'piece', calories: 20 },
  ],
  instructions: ['Boil pasta', 'Toss with lemon'],
  totalCalories: 720,
  caloriesPerServing: 360,
}

// ─── Template model ───────────────────────────────────────────────────────────

test('buildRecipeDocumentTemplate produces a display-ready title and summary block', () => {
  const template = buildRecipeDocumentTemplate(sampleRecipe)

  assert.equal(template.title, 'Lemon Pasta')

  const summary = Object.fromEntries(template.summary.map((fact) => [fact.label, fact.value]))
  assert.equal(summary['Category'], 'Dinner')
  assert.equal(summary['Servings'], '2')
  assert.equal(summary['Total Time'], '25 min')
  assert.equal(summary['Total Calories'], '720 kcal')
  assert.equal(summary['Per Serving'], '360 kcal')
})

test('buildRecipeDocumentTemplate includes the description when present and omits it when blank', () => {
  const withDescription = buildRecipeDocumentTemplate(sampleRecipe)
  assert.equal(withDescription.description, 'Bright weeknight pasta')

  const blank = buildRecipeDocumentTemplate({ ...sampleRecipe, description: '   ' })
  assert.ok(!('description' in blank), 'blank descriptions must be omitted, not blanked out')
})

test('buildRecipeDocumentTemplate omits missing summary facts instead of showing zeros', () => {
  const sparse = buildRecipeDocumentTemplate({
    name: 'Mystery Dish',
    servings: 4,
    ingredients: [],
    instructions: [],
  })

  const labels = sparse.summary.map((fact) => fact.label)
  assert.deepEqual(labels, ['Servings'])
  assert.equal(sparse.summary[0].value, '4')
})

test('buildRecipeDocumentTemplate builds display-ready ingredient rows with neutral calories when missing', () => {
  const template = buildRecipeDocumentTemplate({
    name: 'Mixed',
    ingredients: [
      { name: 'Pasta', amount: 200, unit: 'g', calories: 700 },
      { name: 'Water', amount: 1, unit: 'L' },
      { name: 'Salt', amount: 1, unit: 'pinch', calories: 0 },
    ],
    instructions: [],
  })

  assert.deepEqual(template.ingredients, [
    { name: 'Pasta', amount: '200', unit: 'g', calories: '700 kcal' },
    { name: 'Water', amount: '1', unit: 'L', calories: null },
    { name: 'Salt', amount: '1', unit: 'pinch', calories: '0 kcal' },
  ])
})

test('buildRecipeDocumentTemplate keeps instruction steps and a subtle generated-by footer', () => {
  const template = buildRecipeDocumentTemplate(sampleRecipe)

  assert.deepEqual(template.instructions, ['Boil pasta', 'Toss with lemon'])
  assert.match(template.footer, /Generated by My Cookbook/)
})

// ─── Pass 1: skeleton ─────────────────────────────────────────────────────────

function skeletonText(requests) {
  return requests
    .filter((request) => request.insertText)
    .map((request) => request.insertText.text)
    .join('')
}

test('buildRecipeDocumentSkeleton appends every section without computing indices', () => {
  const requests = buildRecipeDocumentSkeleton(buildRecipeDocumentTemplate(sampleRecipe))

  assert.ok(
    requests.every((request) => !request.insertText || request.insertText.endOfSegmentLocation),
    'skeleton text must be appended, never inserted at a computed index'
  )

  const table = requests.find((request) => request.insertTable)
  assert.ok(table, 'expected a native ingredient table in the skeleton')
  assert.equal(table.insertTable.columns, 4)
  assert.equal(table.insertTable.rows, 3, 'expected a header row plus one row per ingredient')
  assert.ok(table.insertTable.endOfSegmentLocation, 'the table is appended, not placed at an index')

  const text = skeletonText(requests)
  assert.match(text, /Lemon Pasta/)
  assert.match(text, /Bright weeknight pasta/)
  assert.match(text, /Ingredients/)
  assert.match(text, /Instructions/)
  assert.match(text, /Boil pasta/)
  assert.match(text, /Generated by My Cookbook/)
})

test('buildRecipeDocumentSkeleton omits a table and instructions when there are none', () => {
  const requests = buildRecipeDocumentSkeleton(
    buildRecipeDocumentTemplate({ name: 'Just a Note', ingredients: [], instructions: [] })
  )

  assert.equal(requests.some((request) => request.insertTable), false)
  assert.equal(skeletonText(requests).includes('Instructions'), false)
})

// ─── Pass 2: formatting ───────────────────────────────────────────────────────

// Builds a document body content structure that mirrors what the skeleton pass
// produces once Google applies it: real-looking start/end indices for each
// paragraph and table cell. The formatting pass reads these indices back.
function fakeBody(template) {
  const content = []
  let cursor = 1

  const addParagraph = (text) => {
    const body = `${text}\n`
    content.push({
      startIndex: cursor,
      endIndex: cursor + body.length,
      paragraph: { elements: [{ textRun: { content: body } }] },
    })
    cursor += body.length
  }
  const addEmpty = () => {
    content.push({
      startIndex: cursor,
      endIndex: cursor + 1,
      paragraph: { elements: [{ textRun: { content: '\n' } }] },
    })
    cursor += 1
  }
  const addTable = (rows, columns) => {
    const tableStart = cursor
    cursor += 1
    const tableRows = []
    for (let r = 0; r < rows; r += 1) {
      const tableCells = []
      for (let c = 0; c < columns; c += 1) {
        const cellStart = cursor
        tableCells.push({
          content: [
            {
              startIndex: cellStart + 1,
              endIndex: cellStart + 2,
              paragraph: { elements: [{ textRun: { content: '\n' } }] },
            },
          ],
        })
        cursor += 2
      }
      cursor += 1
      tableRows.push({ tableCells })
    }
    content.push({ startIndex: tableStart, endIndex: cursor, table: { rows, columns, tableRows } })
  }

  addParagraph(template.title)
  if (template.description) addParagraph(template.description)
  if (template.summary.length) addParagraph('summary line')
  if (template.ingredients.length) {
    addParagraph('Ingredients')
    addEmpty()
    addTable(template.ingredients.length + 1, 4)
    addEmpty()
  }
  if (template.instructions.length) {
    addParagraph('Instructions')
    for (const step of template.instructions) addParagraph(step)
  }
  if (template.footer) addParagraph(template.footer)

  return content
}

function primaryIndex(request) {
  if (request.insertText) return request.insertText.location.index
  if (request.updateParagraphStyle) return request.updateParagraphStyle.range.startIndex
  if (request.updateTextStyle) return request.updateTextStyle.range.startIndex
  if (request.createParagraphBullets) return request.createParagraphBullets.range.startIndex
  return -1
}

test('buildRecipeDocumentFormatting fills table cells at the indices read back from the document', () => {
  const template = buildRecipeDocumentTemplate(sampleRecipe)
  const body = fakeBody(template)
  const requests = buildRecipeDocumentFormatting(template, body)

  const tableElement = body.find((element) => element.table)
  const cellIndex = (row, col) => tableElement.table.tableRows[row].tableCells[col].content[0].startIndex

  const cellInsert = (value) =>
    requests.find((request) => request.insertText && request.insertText.text === value)

  assert.equal(cellInsert('Ingredient').insertText.location.index, cellIndex(0, 0))
  assert.equal(cellInsert('Pasta').insertText.location.index, cellIndex(1, 0))
  assert.equal(cellInsert('700 kcal').insertText.location.index, cellIndex(1, 3))
  assert.equal(cellInsert('Lemon').insertText.location.index, cellIndex(2, 0))
})

test('buildRecipeDocumentFormatting leaves a neutral cell for ingredients without calories', () => {
  const template = buildRecipeDocumentTemplate({
    name: 'Mixed',
    ingredients: [{ name: 'Water', amount: 1, unit: 'L' }],
    instructions: [],
  })
  const requests = buildRecipeDocumentFormatting(template, fakeBody(template))

  assert.equal(
    requests.some((request) => request.insertText && request.insertText.text === ''),
    false,
    'empty cells must not be filled'
  )
  assert.equal(
    requests.some((request) => request.insertText && request.insertText.text.includes('0 kcal')),
    false,
    'missing per-ingredient calories must not be rendered as 0 kcal'
  )
})

test('buildRecipeDocumentFormatting renders instructions as a native numbered list', () => {
  const template = buildRecipeDocumentTemplate(sampleRecipe)
  const requests = buildRecipeDocumentFormatting(template, fakeBody(template))

  const bullets = requests.find((request) => request.createParagraphBullets)
  assert.ok(bullets, 'expected instructions to use native list bullets')
  assert.match(bullets.createParagraphBullets.bulletPreset, /NUMBERED/)
  assert.ok(
    bullets.createParagraphBullets.range.endIndex > bullets.createParagraphBullets.range.startIndex,
    'the bullet range must cover the step paragraphs'
  )
})

test('buildRecipeDocumentFormatting styles the title, description, summary and footer', () => {
  const template = buildRecipeDocumentTemplate(sampleRecipe)
  const requests = buildRecipeDocumentFormatting(template, fakeBody(template))

  const named = requests
    .filter((request) => request.updateParagraphStyle)
    .map((request) => request.updateParagraphStyle.paragraphStyle.namedStyleType)
  assert.ok(named.includes('TITLE'), 'expected the title to use the TITLE named style')
  assert.ok(named.includes('SUBTITLE'), 'expected the description to use the SUBTITLE named style')

  const subtleCount = requests.filter((request) => request.updateTextStyle).length
  assert.ok(subtleCount >= 2, 'expected the summary line and footer to use restrained styling')
})

test('buildRecipeDocumentFormatting orders requests so cell inserts never invalidate later indices', () => {
  const template = buildRecipeDocumentTemplate(sampleRecipe)
  const requests = buildRecipeDocumentFormatting(template, fakeBody(template))

  const indices = requests.map(primaryIndex)
  const sorted = [...indices].sort((a, b) => b - a)
  assert.deepEqual(indices, sorted, 'requests must be ordered by descending start index')
})
